/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.38
 * Generated at: 2020-07-24 07:33:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/Learn/estor-project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/webapps/estore/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1595208129089L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

  String basePath = request.getScheme() + "://" + request.getServerName() + ":" +
            request.getServerPort() + request.getContextPath() + "/";


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath );
      out.write("\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>briup电子商务-首页</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/common.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/icons.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/table.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--顶部-->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "top.jsp", out, false);
      out.write("\r\n");
      out.write("    <!--头部-->\r\n");
      out.write("    <div class=\"header3\">\r\n");
      out.write("    \t<a href=\"#\"><img src=\"images/logo.png\"></a>\r\n");
      out.write("    \t<div class=\"h3_center\">\r\n");
      out.write("        \t<div class=\"search_box\">\r\n");
      out.write("            \t<input type=\"text\"/>\r\n");
      out.write("                <span>搜索</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p>\r\n");
      out.write("            \t<a href=\"#\">文学类</a>|\r\n");
      out.write("            \t<a href=\"#\">教育类</a>|\r\n");
      out.write("                <a href=\"#\">计算机</a>|\r\n");
      out.write("                <a href=\"#\">儿童类</a>|\r\n");
      out.write("                <a href=\"#\">漫画类</a>|\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"h3_right\">\r\n");
      out.write("        \t<div class=\"myyy\">\r\n");
      out.write("            \t个人信息\r\n");
      out.write("                <span class=\"sj_down\"></span>\r\n");
      out.write("             </div>\r\n");
      out.write("            <div class=\"tsc\">\r\n");
      out.write("            \t<a href=\"user/toShopCarServlet\">去购物车结算</a>\r\n");
      out.write("                <span class=\"sj_right\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--头部导航-->\r\n");
      out.write("    <div class=\"nav_top\">\r\n");
      out.write("    \t<div class=\"nav_top_center\">\r\n");
      out.write("            <div>\r\n");
      out.write("                全部图书分类\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">文学类</a></li>\r\n");
      out.write("                <li><a href=\"#\">教育类</a></li>\r\n");
      out.write("                <li><a href=\"#\">计算机</a></li>\r\n");
      out.write("                <li><a href=\"#\">儿童类</a></li>\r\n");
      out.write("                <li><a href=\"#\">漫画类</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!--内容-->\r\n");
      out.write("    <div class=\"container4\">\r\n");
      out.write("    \t<!--热卖-->\r\n");
      out.write("    \t<div class=\"c4_b1\">\r\n");
      out.write("        \t<ul class=\"c4_b1_boxes\">\r\n");
      out.write("        \t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"c4_b2\">\r\n");
      out.write("            <h1 class=\"c4_b2_x\">\r\n");
      out.write("            \t<a href=\"#\">计算机类&nbsp;&nbsp;></a>\r\n");
      out.write("                <span><a href=\"#\">计算机类</a></span>\r\n");
      out.write("            </h1>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"c4_b2_y\">\r\n");
      out.write("            \t<li>\r\n");
      out.write("                \t<span class=\"search_key\">价格：</span>\r\n");
      out.write("                    <span class=\"search_val\">0-99</span>\r\n");
      out.write("                    <span class=\"search_del\"></span>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                \t<span class=\"search_key\">出版社：</span>\r\n");
      out.write("                    <span class=\"search_val\">清华出版社</span>\r\n");
      out.write("                    <span class=\"search_del\"></span>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"c4_b3\">\r\n");
      out.write("        \t<h1></h1>\r\n");
      out.write("        \t<div>\r\n");
      out.write("            \t<ul class=\"c4_b3_search\">\r\n");
      out.write("                \t<li class=\"c4_b3_name\">价格：</li>\r\n");
      out.write("                    <li class=\"c4_b3_vals\">\r\n");
      out.write("                        <a href=\"#\">0-599</a>\r\n");
      out.write("                        <a href=\"#\">600-999</a>\r\n");
      out.write("                        <a href=\"#\">1000-1599</a>\r\n");
      out.write("                        <a href=\"#\">1600-1999</a>\r\n");
      out.write("                        <a href=\"#\">2000-2999</a>\r\n");
      out.write("                        <a href=\"#\">3000-3999</a>\r\n");
      out.write("                        <a href=\"#\">4000-4999</a>\r\n");
      out.write("                        <a href=\"#\">5000-5999</a>\r\n");
      out.write("                        <a href=\"#\">6000-6490</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("                </ul><ul class=\"c4_b3_search\">\r\n");
      out.write("                \t<li class=\"c4_b3_name\">出版社：</li>\r\n");
      out.write("                    <li class=\"c4_b3_vals\">\r\n");
      out.write("                        <a href=\"#\">清华出版社</a>\r\n");
      out.write("                        <a href=\"#\">清华出版社</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">清华出版社</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">清华出版社</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">清华出版社</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">清华出版社</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    \t<div class=\"c4_b4\">\r\n");
      out.write("        \t<div class=\"c4_b4_x\">\r\n");
      out.write("            \t<ul class=\"c4_b4_nav\">\r\n");
      out.write("                \t<li class=\"current\"><a href=\"#\">默认</a></li>\r\n");
      out.write("                    <li><a href=\"#\">销量</a></li>\r\n");
      out.write("                    <li><a href=\"#\">价格</a></li>\r\n");
      out.write("                    <li><a href=\"#\">新品</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"c4_b4_search\">\r\n");
      out.write("                \t<input type=\"text\"/><span>确认</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"c4_b4_pages\">\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("             <div class=\"c4_b4_y\">\r\n");
      out.write("            \t<ul>\r\n");
      out.write("                    <li><input type=\"checkbox\"> 仅显示有货</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("       \t</div>\r\n");
      out.write("    \t<!--商品列表-->\r\n");
      out.write("        <div class=\"c4_b5\">\r\n");
      out.write("        \t<div class=\"c4_b5_content\">\r\n");
      out.write("            \t<ul class=\"c4_b5_c_boxes\">\r\n");
      out.write("            \t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("      \r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--脚部-->\r\n");
      out.write("    <div class=\"footer3\">\r\n");
      out.write("    \t<div class=\"f3_top\">\r\n");
      out.write("        \t<div class=\"f3_center\">\r\n");
      out.write("                <div class=\"ts1\">品目繁多 愉悦购物</div>\r\n");
      out.write("                <div class=\"ts2\">正品保障 天天低价</div>\r\n");
      out.write("                <div class=\"ts3\">极速物流 特色定制</div>\r\n");
      out.write("                <div class=\"ts4\">优质服务 以客为尊</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"f3_middle\">\r\n");
      out.write("        \t<ul class=\"f3_center\">\r\n");
      out.write("            \t<li class=\"f3_mi_li01\">\r\n");
      out.write("                \t<h1>购物指南</h1>\r\n");
      out.write("                    <p>常见问题</p>\r\n");
      out.write("                    <p>找回密码</p>\r\n");
      out.write("                    <p>会员介绍</p>\r\n");
      out.write("                    <p>购物演示</p>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"f3_mi_li01\">\r\n");
      out.write("                \t<h1>配送方式</h1>\r\n");
      out.write("                    <p>常见问题</p>\r\n");
      out.write("                    <p>找回密码</p>\r\n");
      out.write("                    <p>会员介绍</p>\r\n");
      out.write("                    <p>购物演示</p>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"f3_mi_li01\">\r\n");
      out.write("                \t<h1>支付方式</h1>\r\n");
      out.write("                    <p>常见问题</p>\r\n");
      out.write("                    <p>找回密码</p>\r\n");
      out.write("                    <p>会员介绍</p>\r\n");
      out.write("                    <p>购物演示</p>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"f3_mi_li01\">\r\n");
      out.write("                \t<h1>售后服务</h1>\r\n");
      out.write("                    <p>常见问题</p>\r\n");
      out.write("                    <p>找回密码</p>\r\n");
      out.write("                    <p>会员介绍</p>\r\n");
      out.write("                    <p>购物演示</p>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"f3_mi_li01\">\r\n");
      out.write("                \t<h1>服务保障</h1>\r\n");
      out.write("                    <p>常见问题</p>\r\n");
      out.write("                    <p>找回密码</p>\r\n");
      out.write("                    <p>会员介绍</p>\r\n");
      out.write("                    <p>购物演示</p>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"f3_mi_li06\">\r\n");
      out.write("                \t<h1>客服中心</h1>\r\n");
      out.write("                    <img src=\"images/qrcode_jprj.jpg\" width=\"80px\" height=\"80px\">\r\n");
      out.write("                    <p>抢红包、疑问咨询、优惠活动</p>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("         <div class=\"f3_bottom\">\r\n");
      out.write("        \t<p class=\"f3_links\">\r\n");
      out.write("                <a href=\"#\">关于我们</a>|\r\n");
      out.write("                <a href=\"#\">联系我们</a>|\r\n");
      out.write("                <a href=\"#\">友情链接</a>|\r\n");
      out.write("                <a href=\"#\">供货商入驻</a>\r\n");
      out.write("           \t</p>\r\n");
      out.write("            <p>沪ICP备14033591号-8 杰普briup.com版权所有 杰普软件科技有限公司 </p>\r\n");
      out.write("          \t<img src=\"images/police.png\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/jsp/list.jsp(71,9) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topBooklist }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/jsp/list.jsp(71,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("book");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("            \t<li>\r\n");
            out.write("                \t<img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.image }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                    <div class=\"c4_b1_box_txt\">\r\n");
            out.write("                    \t<p>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </p>\r\n");
            out.write("                        <h1>活动价：<b>￥");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</b></h1>\r\n");
            out.write("                        <h2><a href=\"View?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">立即抢购</a></h2>\r\n");
            out.write("                    </div>\r\n");
            out.write("                </li>\r\n");
            out.write("\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/jsp/list.jsp(157,13) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booklist }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/jsp/list.jsp(157,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("book");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                \t<li class=\"c4_b5_c_box\">\r\n");
            out.write("                    \t<!--图片-->\r\n");
            out.write("                    \t<div class=\"c4_b5_c_box_pic\">\r\n");
            out.write("                        \t<div class=\"c4b5_pic_view\">\r\n");
            out.write("                            \t<a href=\"View?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.image }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"></a>\r\n");
            out.write("                            </div>\r\n");
            out.write("                        </div>\r\n");
            out.write("                        <!--价钱-->\r\n");
            out.write("                        <div class=\"c4_b5_c_box_txt\">\r\n");
            out.write("                        \t<h1>￥ \"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"</h1>\r\n");
            out.write("                            <h2><a href=\"View?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write('"');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"</a></h2>\r\n");
            out.write("                        </div>\r\n");
            out.write("                        <!--购买等操作-->\r\n");
            out.write("                        <div class=\"c4b5_el\">\r\n");
            out.write("                        \t<div class=\"c4b5_el_x\">\r\n");
            out.write("                            \t<span class=\"wjx01\"></span>\r\n");
            out.write("                            </div>\r\n");
            out.write("                        </div>\r\n");
            out.write("                        <ul class=\"c4b5_option\">\r\n");
            out.write("                                <li class=\"shopcar_box\"><span class=\"shopcar01\"></span><a href=\"View?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">加入购物车</a></li>\r\n");
            out.write("                        </ul>\r\n");
            out.write("                    </li>\r\n");
            out.write("               ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
