/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.38
 * Generated at: 2020-07-24 06:11:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

  String basePath = request.getScheme() + "://" + request.getServerName() + ":" +
            request.getServerPort() + request.getContextPath() + "/";


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath );
      out.write("\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>briup电子商务-登录页</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/common.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"header1\">\r\n");
      out.write("    \t<a href=\"#\">\r\n");
      out.write("        \t<img src=\"images/logo.png\">\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"content1\">\t<!--背景颜色-->\r\n");
      out.write("    \t<div class=\"c1_box1\"><!--背景图片-->\r\n");
      out.write("        \t<div class=\"login_box\"><!--登陆框-->\r\n");
      out.write("            \t<div class=\"center1\">\r\n");
      out.write("        \t\t<form action=\"loginServlet\" method=\"post\">\r\n");
      out.write("                \t<h1>账号登陆</h1>\r\n");
      out.write("                    <h2>公共场所请不要泄露您的密码，以防止账号丢失\r\n");
      out.write("                    </h2>\r\n");
      out.write("                    <div class=\"si_box\">\r\n");
      out.write("                    \t<span class=\"usr_icon\"></span>\r\n");
      out.write("                        <input type=\"text\" name=\"name\"/>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!--分割条-->\r\n");
      out.write("                    <div class=\"c10\"></div>\r\n");
      out.write("                    <div class=\"si_box\">\r\n");
      out.write("                    \t<span class=\"pwd_icon\"></span>\r\n");
      out.write("                        <input type=\"password\" name=\"password\"/>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"fg_box\">\r\n");
      out.write("                        <a class=\"treg\" href=\"toRegisterServlet\">立即注册</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"sub_box\">\r\n");
      out.write("                    \t<input type=\"submit\" value=\"登陆\"/>\r\n");
      out.write("                    </div>\r\n");
      out.write("                 </form>\r\n");
      out.write("                    <div>\r\n");
      out.write("                    \t请使用合作网站账号登陆杰普电子商务网：\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"com_box\">\r\n");
      out.write("                    \t<span class=\"tencent\"></span>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer1\">\r\n");
      out.write("    \t<div class=\"links\">\r\n");
      out.write("        \t<a href=\"#\">关于我们</a>|\r\n");
      out.write("            <a href=\"#\">联系我们</a>|\r\n");
      out.write("            <a href=\"#\">友情链接</a>|\r\n");
      out.write("            <a href=\"#\">关于我们</a>|\r\n");
      out.write("            <a href=\"#\">联系我们</a>|\r\n");
      out.write("            <a href=\"#\">友情链接</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("        \t沪ICP备1928832 杰普软件briup.com版权所有。\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <img src=\"images/police.png\">\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
