/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.38
 * Generated at: 2020-07-24 07:32:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class viewBook_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

  String basePath = request.getScheme() + "://" + request.getServerName() + ":" +
            request.getServerPort() + request.getContextPath() + "/";


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath );
      out.write("\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>briup电子商务-首页</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/common.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/icons.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/table.css\" />\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction reduceCount(){\r\n");
      out.write("\t\tvar numObj = document.getElementsByName(\"num\")[0];\r\n");
      out.write("\t\tif(parseInt(numObj.value)>1){\r\n");
      out.write("\t\t\tnumObj.value = parseInt(numObj.value)-1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction addCount(){\r\n");
      out.write("\t\tvar numObj = document.getElementsByName(\"num\")[0];\r\n");
      out.write("\t\tnumObj.value = parseInt(numObj.value)+1;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction submitForm(){\r\n");
      out.write("\t\tdocument.getElementById(\"addCar\").submit();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--顶部-->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "top.jsp", out, false);
      out.write("\r\n");
      out.write("    <!--头部-->\r\n");
      out.write("    <div class=\"header3\">\r\n");
      out.write("    \t<a href=\"#\"><img src=\"images/logo.png\"></a>\r\n");
      out.write("    \t<div class=\"h3_center\">\r\n");
      out.write("        \t<div class=\"search_box\">\r\n");
      out.write("            \t<input type=\"text\"/>\r\n");
      out.write("                <span>搜索</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p>\r\n");
      out.write("            \t<a href=\"#\">文学类</a>|\r\n");
      out.write("            \t<a href=\"#\">教育类</a>|\r\n");
      out.write("                <a href=\"#\">计算机</a>|\r\n");
      out.write("                <a href=\"#\">儿童类</a>|\r\n");
      out.write("                <a href=\"#\">漫画类</a>|\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"h3_right\">\r\n");
      out.write("        \t<div class=\"myyy\">\r\n");
      out.write("            \t个人信息\r\n");
      out.write("                <span class=\"sj_down\"></span>\r\n");
      out.write("             </div>\r\n");
      out.write("            <div class=\"tsc\">\r\n");
      out.write("            \t<a href=\"user/toShopCarServlet\">去购物车结算</a>\r\n");
      out.write("                <span class=\"sj_right\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--头部导航-->\r\n");
      out.write("    <div class=\"nav_top\">\r\n");
      out.write("    \t<div class=\"nav_top_center\">\r\n");
      out.write("            <div>\r\n");
      out.write("                全部图书分类\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">文学类</a></li>\r\n");
      out.write("                <li><a href=\"#\">教育类</a></li>\r\n");
      out.write("                <li><a href=\"#\">计算机</a></li>\r\n");
      out.write("                <li><a href=\"#\">儿童类</a></li>\r\n");
      out.write("                <li><a href=\"#\">漫画类</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container5\">\r\n");
      out.write("    \t<div class=\"cn5_top\">\r\n");
      out.write("            <div class=\"cn5_top_x center01\">\r\n");
      out.write("            \t<a class=\"font20\" href=\"#\">书籍</a> >\r\n");
      out.write("                <a href=\"#\">计算机类</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"cn5_top_y center01\">\r\n");
      out.write("            \t<div class=\"cn5topy_1\">\r\n");
      out.write("                \t<div class=\"cn5topy_imgview\">\r\n");
      out.write("                    \t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.image }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                        <!-- <ul class=\"cn5topy_imglist\">\r\n");
      out.write("                        \t<li><a href=\"#\"><img src=\"images/viewBook.png\"></a></li>\r\n");
      out.write("                            <li class=\"current\"><a href=\"#\"><img src=\"images/viewBook.png\"></a></li>\r\n");
      out.write("                            <li><a href=\"#\"><img src=\"images/viewBook.png\"></a></li>\r\n");
      out.write("                            <li><a href=\"#\"><img src=\"images/viewBook.png\"></a></li>\r\n");
      out.write("                            <li><a href=\"#\"><img src=\"images/viewBook.png\"></a></li>\r\n");
      out.write("                        </ul> -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"cn5topy_2\">\r\n");
      out.write("                \t<h1 class=\"pro_title font15\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\r\n");
      out.write("                    <div class=\"pro_price\">\r\n");
      out.write("                            <div class=\"pro_price_x\">\r\n");
      out.write("                                <p> briup价：<b>￥");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b> <a href=\"#\">(降价通知)</a></p>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- <div>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><span>作者：</span>托马斯</li>\r\n");
      out.write("                            <li></li>\r\n");
      out.write("                            <li></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div> -->\r\n");
      out.write("                    <div class=\"pro_selects\">\r\n");
      out.write("                    \t<div class=\"pro_select\">\r\n");
      out.write("                        \t<div class=\"pro_key pro_key_vertical fl\">作者：</div>\r\n");
      out.write("                            <ul class=\"pro_select_vals\">\r\n");
      out.write("                                <li>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.author }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"pro_select\">\r\n");
      out.write("                            <div class=\"pro_key pro_key_vertical fl\">出版社：</div>\r\n");
      out.write("                            <ul class=\"pro_select_vals\">\r\n");
      out.write("                                <li> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.publisher }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"pro_select\">\r\n");
      out.write("                            <div class=\"pro_key pro_key_vertical fl\">书籍介绍：</div>\r\n");
      out.write("                            <ul class=\"pro_select_vals\">\r\n");
      out.write("                                <li> 出版时间：");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.pubDate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\r\n");
      out.write("                                <li>包装：平装</li>\r\n");
      out.write("                                <li>正文语种：中文</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\t\t\t\t<form action=\"user/addShopCarServlet\" id=\"addCar\">\r\n");
      out.write("                    <div class=\"pro_buy\">\r\n");
      out.write("                    \t<div class=\"pro_buy_nums\">\r\n");
      out.write("                    \t\t<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"id\">\r\n");
      out.write("                        \t<input type=\"text\" value=\"1\" name=\"num\"/>\r\n");
      out.write("                            <dl>\r\n");
      out.write("                            \t<dd onclick=\"addCount()\">+</dd>\r\n");
      out.write("                                <dd onclick=\"reduceCount()\">-</dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                        </div>\r\n");
      out.write("                       <!--  <div class=\"pro_addshop\" onclick=\"submitForm()\">加入购物车</div> -->\r\n");
      out.write("\t\t\t\t\t\t<!--  <div class=\"pro_addshop\"><a href=\"user/ddShopCarServlet\">加入购物车</a></div> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("                    \t\t<div class=\"pro_addshop\" ><input type=\"submit\" value=\"加入购物车\"></div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("                    <div class=\"pro_ship\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div class=\"pro_key fl\">服&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;务：</div>\r\n");
      out.write("                            <ul class=\"pro_service f1\">\r\n");
      out.write("                                <li class=\"service_fq\">分期付款</li>\r\n");
      out.write("                                <li class=\"service_myf\">免运费</li>\r\n");
      out.write("                                <li class=\"service_zt\">自提</li>\r\n");
      out.write("                                <li class=\"service_th\">7天无理由退换货</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    \t<div class=\"c5_b2\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"c5_b2_right\">\r\n");
      out.write("            \t<!--选项卡-->\r\n");
      out.write("            \t<ul class=\"c5_b2_tabs\">\r\n");
      out.write("                \t<li>商品介绍</li>\r\n");
      out.write("                    <li class=\"current\">规格参数</li>\r\n");
      out.write("                    <li>包装清单</li>\r\n");
      out.write("                    <li>商品评价</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <!--内容-->\r\n");
      out.write("              \t<div class=\"c5_b2_right_1 box\">\r\n");
      out.write("                        <div class=\"introduce_item\">\r\n");
      out.write("                          <ul>\r\n");
      out.write("                        \t<li>商品名称：Effective Java (中文版) 第2版</li>\r\n");
      out.write("                            <li>商品编号：1002024</li>\r\n");
      out.write("                            <li class=\"fr\"><a class=\"color_link1\" href=\"#\">更多参数>></a></li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("               \t\t</div>\r\n");
      out.write("                    <div class=\"intro_pics\">\r\n");
      out.write("                    \t<img class=\"intro_pic\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.image }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"c5_b2_right\">\r\n");
      out.write("              \t<div class=\"c5_b2_right_2\">\r\n");
      out.write("                    \t<h1>正品行货</h1>\r\n");
      out.write("                        <p>briup网上商城向您保证所售商品均为正品，briup自营商品开具机打发票或电子发票。</p>\r\n");
      out.write("\r\n");
      out.write("                        <h1>全国联保</h1>\r\n");
      out.write("                        <p>凭质保证书及briup网上商城发票，可享受全国联保服务，与您亲临商场选购的商品享受相同的质量保证。briup网上商城还为您提供具有竞争力的商品价格和运费政策，请您放心购买！</p>\r\n");
      out.write("\r\n");
      out.write("                        <h1>正品行货</h1>\r\n");
      out.write("                        <p>briup网上商城向您保证所售商品均为正品，briup自营商品开具机打发票或电子发票。</p>\r\n");
      out.write("\r\n");
      out.write("                        <h1>全国联保</h1>\r\n");
      out.write("                        <p>凭质保证书及briup网上商城发票，可享受全国联保服务，与您亲临商场选购的商品享受相同的质量保证。briup网上商城还为您提供具有竞争力的商品价格和运费政策，请您放心购买！</p>\r\n");
      out.write("\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!--左侧栏-->\r\n");
      out.write("            <div class=\"c5_b2_left_container\">\r\n");
      out.write("                <div class=\"c5_b2_left box\">\r\n");
      out.write("                    <h1>服务时间 早9：00~凌晨1：00</h1>\r\n");
      out.write("                    <p>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <img class=\"callmebyqq\" src=\"images/icon_qq_03.png\"/>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"c5_b2_left box\">\r\n");
      out.write("                    <h1>其他种类</h1>\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dd>文学类</dd>\r\n");
      out.write("                        <dd>漫画类</dd>\r\n");
      out.write("                        <dd>通书类</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dd>文学类</dd>\r\n");
      out.write("                        <dd>漫画类</dd>\r\n");
      out.write("                        <dd>通书类</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"c20\"></div>\r\n");
      out.write("    <!--脚部-->\r\n");
      out.write("    <div class=\"footer3\">\r\n");
      out.write("    \t<div class=\"f3_top\">\r\n");
      out.write("        \t<div class=\"f3_center\">\r\n");
      out.write("                <div class=\"ts1\">品目繁多 愉悦购物</div>\r\n");
      out.write("                <div class=\"ts2\">正品保障 天天低价</div>\r\n");
      out.write("                <div class=\"ts3\">极速物流 特色定制</div>\r\n");
      out.write("                <div class=\"ts4\">优质服务 以客为尊</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"f3_middle\">\r\n");
      out.write("        \t<ul class=\"f3_center\">\r\n");
      out.write("            \t<li class=\"f3_mi_li01\">\r\n");
      out.write("                \t<h1>购物指南</h1>\r\n");
      out.write("                    <p>常见问题</p>\r\n");
      out.write("                    <p>找回密码</p>\r\n");
      out.write("                    <p>会员介绍</p>\r\n");
      out.write("                    <p>购物演示</p>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"f3_mi_li01\">\r\n");
      out.write("                \t<h1>配送方式</h1>\r\n");
      out.write("                    <p>常见问题</p>\r\n");
      out.write("                    <p>找回密码</p>\r\n");
      out.write("                    <p>会员介绍</p>\r\n");
      out.write("                    <p>购物演示</p>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"f3_mi_li01\">\r\n");
      out.write("                \t<h1>支付方式</h1>\r\n");
      out.write("                    <p>常见问题</p>\r\n");
      out.write("                    <p>找回密码</p>\r\n");
      out.write("                    <p>会员介绍</p>\r\n");
      out.write("                    <p>购物演示</p>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"f3_mi_li01\">\r\n");
      out.write("                \t<h1>售后服务</h1>\r\n");
      out.write("                    <p>常见问题</p>\r\n");
      out.write("                    <p>找回密码</p>\r\n");
      out.write("                    <p>会员介绍</p>\r\n");
      out.write("                    <p>购物演示</p>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"f3_mi_li01\">\r\n");
      out.write("                \t<h1>服务保障</h1>\r\n");
      out.write("                    <p>常见问题</p>\r\n");
      out.write("                    <p>找回密码</p>\r\n");
      out.write("                    <p>会员介绍</p>\r\n");
      out.write("                    <p>购物演示</p>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"f3_mi_li06\">\r\n");
      out.write("                \t<h1>客服中心</h1>\r\n");
      out.write("                    <img src=\"images/qrcode_jprj.jpg\" width=\"80px\" height=\"80px\">\r\n");
      out.write("                    <p>抢红包、疑问咨询、优惠活动</p>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"f3_bottom\">\r\n");
      out.write("        \t<p class=\"f3_links\">\r\n");
      out.write("                <a href=\"#\">关于我们</a>|\r\n");
      out.write("                <a href=\"#\">联系我们</a>|\r\n");
      out.write("                <a href=\"#\">友情链接</a>|\r\n");
      out.write("                <a href=\"#\">供货商入驻</a>\r\n");
      out.write("           \t</p>\r\n");
      out.write("            <p>沪ICP备14033591号-8 杰普briup.com版权所有 杰普软件科技有限公司 </p>\r\n");
      out.write("          \t<img src=\"images/police.png\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
